### PR TITLE
jhbuildrc: fix wrong location of jhbuild

### PR DESCRIPTION
**Pull request by justinjoy**
According to jhbuild manual, it will be located in ".local", not "local".

### CODE REVIEW

**Comment by justinjoy** [comment]
If this is acceptable, please fix gstreamer-1.2.jhbuildrc also.

**Comment by justinjoy** [comment]
hahaha, shame on me. I got tangled in my git branches.

**Comment by joybro** [comment]
@justinjoy, I encountered a problem caused by this INSTALL environment variable and fixed it other way(a7ee3734b1cc373ad74353f6eac073dc373d59a1)

install-check is installed together with jhbuild. So I think we must not specify a path for that because we didn't specify a path for jhbuild.

**Comment by justinjoy** [comment]
then, we can close this.

**Pull request closed without merging**
